# START WITH PREPACKAGED NGINX BUILD IMAGE
FROM nginx:mainline-alpine3.18-slim

LABEL maintainer="Julian Raymar <julian.raymar@zeel.com>"

# Add necessary alpine packages
RUN set -eux; \
	\
	apk add --no-cache --virtual .build-deps \
	    python3-dev \
	    py3-pip \
	    uwsgi-python3 \
	    supervisor \
	    build-base \
		gnupg \
		gcc \
		linux-headers \
	; \
	python3 --version \
	pip --version

CMD ["python3"]

# START NGINX CONFIG
ENV NGINX_MAX_UPLOAD 0

# By default, Nginx will run a single worker process, setting it to auto
# will create a worker for each CPU core
ENV NGINX_WORKER_PROCESSES 1

# By default, run 2 processes
ENV UWSGI_CHEAPER 2

# By default, when on demand, run up to 16 processes
ENV UWSGI_PROCESSES 16

# By default, Nginx listens on port 80.
# To modify this, change LISTEN_PORT environment variable.
# (in a Dockerfile or with an option for `docker run`)
ENV LISTEN_PORT 80

# Expose 80 for normal web traffic
EXPOSE 80

# Expose 443, in case of LTS / HTTPS
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
